name: Terraform Dev Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: hopeful-list-446012-q4
  REGION: us-central1
  AR_REPO: weather-app
  IMAGE_NAME: weather
  SERVICE_ACCOUNT: github-actions-deployer@hopeful-list-446012-q4.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout infra repo
      - name: Checkout Infra Repo
        uses: actions/checkout@v4

      # 2️⃣ Checkout application repo
      - name: Checkout App Repo
        uses: actions/checkout@v4
        with:
          repository: binitbaral/application-code
          path: app

      # 3️⃣ Authenticate to GCP using WIF
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/974490845585/locations/global/workloadIdentityPools/github-pool2/providers/github-provider
          service_account: github-actions-deployer@hopeful-list-446012-q4.iam.gserviceaccount.com

      # 4️⃣ Setup gcloud
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # 5️⃣ Configure Docker auth
      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # 6️⃣ Build & Push Docker Image
      - name: Build and Push Image
        run: |
          docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/$AR_REPO/$IMAGE_NAME:latest ./app
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/$AR_REPO/$IMAGE_NAME:latest

      # 7️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 8️⃣ Terraform Init
      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init -input=false

      # 9️⃣ Terraform Apply
      - name: Terraform Apply
        working-directory: environments/dev
        run: terraform apply -auto-approve -input=false
